### ISSUE TITLE
 cannot find package

### ISSUE THREAD

**Issue by lovecn** [wuxiaoxiaoshen/fakeuseragent#1]
```js
git clone https://github.com/wuxiaoxiaoshen/fakeuseragent
cd fakeuseragent
[root@su fakeuseragent]# go run test.go
test.go:6:2: cannot find package "github.com/wuxiaoxiaoshen/fakeuseragent/application" in any of:
        /usr/lib/golang/src/github.com/wuxiaoxiaoshen/fakeuseragent/application (from $GOROOT)
        /root/go/src/github.com/wuxiaoxiaoshen/fakeuseragent/application (from $GOPATH)
[root@su fakeuseragent]# cat test.go
package main

import (
        "fmt"

        "github.com/wuxiaoxiaoshen/fakeuseragent/application"
)

func main() {
        fakeUserAgent := application.NewFakeUserAgent(false)
        fmt.Println(fakeUserAgent.Random())
        fmt.Println(fakeUserAgent.Safari())
        fmt.Println(fakeUserAgent.Chrome())
        fmt.Println(fakeUserAgent.IE())
        fmt.Println(fakeUserAgent.Opera())
}
```

**Comment by wuxiaoxiaoshen** [comment]
> ```js
> git clone https://github.com/wuxiaoxiaoshen/fakeuseragent
> cd fakeuseragent
> [root@su fakeuseragent]# go run test.go
> test.go:6:2: cannot find package "github.com/wuxiaoxiaoshen/fakeuseragent/application" in any of:
>         /usr/lib/golang/src/github.com/wuxiaoxiaoshen/fakeuseragent/application (from $GOROOT)
>         /root/go/src/github.com/wuxiaoxiaoshen/fakeuseragent/application (from $GOPATH)
> [root@su fakeuseragent]# cat test.go
> package main
> 
> import (
>         "fmt"
> 
>         "github.com/wuxiaoxiaoshen/fakeuseragent/application"
> )
> 
> func main() {
>         fakeUserAgent := application.NewFakeUserAgent(false)
>         fmt.Println(fakeUserAgent.Random())
>         fmt.Println(fakeUserAgent.Safari())
>         fmt.Println(fakeUserAgent.Chrome())
>         fmt.Println(fakeUserAgent.IE())
>         fmt.Println(fakeUserAgent.Opera())
> }
> ```

go get github.com/wuxiaoxiaoshen/fakeuseragent/application
